---
- hosts: all
  sudo: yes

  tasks:
  - name: change into directory and add block in VagrantFile
    blockinfile:
      path: /home/vagrant/VM1/Vagrantfile
      insertbefore: Vagrant.configure("2") do |config|
      block: |
        config.vm.network "private_network", ip: "192.168.33.12"
          config.vm.provision "ansible" do |ansible|
          ansible.verbose = "v"
          ansible.playbook = "iTrust.yml"
        end
  - name: Provision vm1
    script: provision.sh

  - name: Do vagrant up
    become: yes
    command: chdir=/home/vagrant/VM1 vagrant up

