---
- hosts: all
  sudo: yes

  tasks:
  - name: Add Oracle VirtualBox official repository to sources.list
    blockinfile:
      path: /etc/apt/sources.list
      block: deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib

  - name: downloading the key and adding it to key-ring for secure apt
    apt_key:
      url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
      state: present

  - name: update sfw sources and install VBox-5.0
    apt:
      update_cache: yes
      name: virtualbox-5.0
      state: present
      force: yes

  - name: change into directory and add block in VagrantFile
    blockinfile:
      path: /home/vagrant/VM1/Vagrantfile
      insertbefore: Vagrant.configure("2") do |config|
      block: |
        config.vm.network "private_network", ip: "192.168.33.12"
          config.vm.provision "ansible" do |ansible|
          ansible.verbose = "v"
          ansible.playbook = "iTrust.yml"
        end
  - name: Provision vm1
    script: provision.sh

  - name: Do vagrant up
    become: yes
    command: chdir=/home/vagrant/VM1 vagrant up

